vpc_cidr_block          = "10.0.0.0/16"
vpc_name                = "tu-vpc"
sn_public_cidr_block    = "10.0.1.0/24"
sn_private_cidr_block   = "10.0.5.0/24"
az_public               = "us-west-1a"
az_private              = "us-west-1b"