name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Terraform Apply
    runs-on: mock-project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Unzip & Node.js)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve | tee terraform-apply.log

      - name: Upload Terraform Apply Output
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-output
          path: terraform-apply.log
